### ISSUE TITLE
Unable to initialize Next.js project with WunderGraph

### ISSUE THREAD

**Issue by UcheAzubuko** [wundergraph/wunderctl#4]
Hi! I'd like to get assistance with initializing a Next.js project with WunderGraph on my local machines (Windows and Mac).

I have globally installed the WunderGraph CLI, using yarn, but when I run `wunderctl init --template nextjs-starter`, I get an error like shown in the attached screenshot:

![image](https://user-images.githubusercontent.com/32451312/194175127-705b18e1-4534-40e4-97d9-0b1e91663955.png)

**Comment by liuwei0514** [comment]
use npm instand of yarn 
老哥，试试用npm i ，用yarn会报错，提示 Could not find binary in node_modules/@wundergraph/wunderctl/download/wunderctl.
